name: Repository Events
on: 
  push:
      branches:
          - main
          - "feature/*"
          - "feature/**"
          - "!feature/new-branch"
      tags:
          - v1.*
          - '!v1.1.1'
      paths:
          - "**.js"
  pull_request:
    types: [opened, assigned, reopened, synchronize]
  issues:
    types: [opened]

jobs:
  checkout-test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo $GITHUB_SHA
          echo $GITHUB_REF
      - uses: actions/checkout@v3