name: Stale Issues and PRs
on:
    schedule:
        - cron: "0 0 * * *"

jobs:
    stale:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/stale@v8
            with:
                stale-issue-message: "Message"
                days-before-stale: 1
                days-before-close: 5